apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-backend
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-backend
  template:
    metadata:
      labels:
        app: webapp-backend
    spec:
      containers:
      - name: backend
        image: yourdockerhubusername/webapp-backend:latest
        ports:
        - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
      - name: frontend
        image: yourdockerhubusername/webapp-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://webapp-backend.webapp.svc.cluster.local:5000"
