apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
      - name: frontend
        image: agrawalankit110/stepup:frontend_v1
        ports:
        - containerPort: 3000