name: Build and Push Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: frontend
            context: ./kaam_webapp
            dockerfile: ./kaam_webapp/Dockerfile
          - name: backend
            context: ./kaam-backend
            dockerfile: ./kaam-backend/Dockerfile
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ${{ matrix.name }} image
      run: |
        IMAGE_TAG="agrawalankit110/stepup:${{ matrix.name }}_v${{ github.run_number }}"
        echo "Building and pushing $IMAGE_TAG"
        docker build -f ${{ matrix.dockerfile }} ${{ matrix.context }} -t $IMAGE_TAG
        docker push $IMAGE_TAG
